### ISSUE TITLE
TypeError: 'map' object is not subscriptable

### ISSUE THREAD

**Issue by iQBotProject** [llSourcell/Q-Learning-for-Trading#8]
![image](https://user-images.githubusercontent.com/32252265/64506197-8c45ee80-d2ce-11e9-8015-5667a94e5829.png)

please help me to pass this problem , i use /run.py --mode train
@llSourcell @IsaacPatole @AntoineMath @S0AndS0

**Comment by S0AndS0** [comment]
Greetings @yesamine and welcome to GitHub,


Looks like you've closed this issue, hopefully that means that it's been resolved; if so please add an edit to your OP on what fixed it (so future readers that stumble across this thread have a solution), if not then please re-open this issue (so that those mentioned know that it's still on-going).

I took a trace through the source code and gander at other issues on this repository, and didn't see anything that jumped out.


Good luck exploiting the markets with ML!
